{
  "completed_status": "Fail",
  "current_step": 0,
  "eplusout_err": [
    "Program Version,EnergyPlus, Version 24.1.0-9d7789a3ac, ",
    "   ** Warning ** PluginManager: Search path inputs requested adding epin variable to Python path, but epin variable was empty, skipping.",
    "   ************* Successfully added path \"/home/julien/Software/Others/OpenStudio-resources/testruns/python_plugin.py/files\" to the sys.path in Python",
    "   ** Severe  ** Failed to import module \"python_plugin_program\"",
    "   **   ~~~   ** Current sys.path=[\"/home/julien/Software/Others/OpenStudio-resources/testruns/python_plugin.py/files\", \"./\", \".\", \"/usr/local/openstudio-3.8.0/EnergyPlus\", \"/usr/local/openstudio-3.8.0/EnergyPlus/python_standard_lib/lib-dynload\", \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python38.zip\", \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8\", \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/lib-dynload\", \"/usr/local/openstudio-3.8.0/EnergyPlus/python_standard_lib\"]",
    "   **   ~~~   ** Python error description follows: ",
    "   **   ~~~   ** ImportError('libffi.so.7: cannot open shared object file: No such file or directory')",
    "   **   ~~~   ** Python traceback follows: ",
    "   **   ~~~   ** ```",
    "   **   ~~~   **  >>> Traceback (most recent call last):",
    "   **   ~~~   **  >>>   File \"/home/julien/Software/Others/OpenStudio-resources/testruns/python_plugin.py/files/python_plugin_program.py\", line 1, in <module>",
    "    from pyenergyplus.plugin import EnergyPlusPlugin",
    "   **   ~~~   **  >>>   File \"/usr/local/openstudio-3.8.0/EnergyPlus/pyenergyplus/plugin.py\", line 62, in <module>",
    "    from pyenergyplus.api import EnergyPlusAPI",
    "   **   ~~~   **  >>>   File \"/usr/local/openstudio-3.8.0/EnergyPlus/pyenergyplus/api.py\", line 56, in <module>",
    "    from ctypes import cdll, c_char_p, c_void_p",
    "   **   ~~~   **  >>>   File \"/usr/local/openstudio-3.8.0/EnergyPlus/python_standard_lib/ctypes/__init__.py\", line 7, in <module>",
    "    from _ctypes import Union, Structure, Array",
    "   **   ~~~   **  >>> ImportError: libffi.so.7: cannot open shared object file: No such file or directory",
    "   **   ~~~   ** ```",
    "   **  Fatal  ** Python import error causes program termination",
    "   ...Summary of Errors that led to program termination:",
    "   ..... Reference severe error count=1",
    "   ..... Last severe error=Failed to import module \"python_plugin_program\"",
    "   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).",
    "   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.",
    "   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.",
    "   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.",
    "   ************* EnergyPlus Terminated--Fatal Error Detected. 0 Warning; 1 Severe Errors; "
  ],
  "file_paths": [
    "/home/julien/Software/Others/OpenStudio-resources/testruns/python_plugin.py/generated_files",
    "./files",
    "./weather",
    "../../files",
    "../../weather",
    "./"
  ],
  "run_options": null,
  "seed_file": "in.osm",
  "steps": [
    {
      "arguments": {
      },
      "measure_dir_name": "openstudio_results"
    }
  ],
  "weather_file": "../../weatherdata/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw"
}